#!/usr/bin/env bash 
#
# Remove those 'obsolete' local git branches that are no longer exist on the remote repository 
#

# Make sure you are under a git repository
if ! (git rev-parse --is-inside-work-tree > /dev/null 2>&1); then 
	echo "Not in a git repository"
	exit 1
fi

# Do a prune fetch 
git fetch -p

# Figure out the list of local branches that are no longer existing on the remote 
branches=$(git branch -vv | grep ': gone]' | awk '{ print $1 }')

if [ -z $branches ]; then
	echo "No obsolete local branch is found - You are all good."
	exit 0 
fi

echo -e "The following local branches (no longer exist on the remote) will be removed:\n" 
echo -e "$branches \n" 
read -p "Proceed? [Yy/Nn]" answer
case $answer in 
	[Yy]* ) ;;
	[Nn]* ) exit 0 ;;
	*) echo "Please answer yes or no."; exit 0 ;;
esac

# Recursively remove 'obsolete' local branches 
for b in $branches
do
	git branch -D $b
done
